import { Geist, Geist_Mono } from "next/font/google";
import { Luckiest_Guy, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/component/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const luckiestGuy = Luckiest_Guy({
  variable: "--font-luckiest-guy",
  subsets: ["latin"],
  weight: "400",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      suppressHydrationWarning
      className="overflow-x-hidden">
      <head>
        <meta name="color-scheme" content="light only" />
      </head>
      <body
        style={{
          colorScheme: "light",
          background: "white",
          backgroundColor: "white",
        }}
        className={`${geistSans.variable} ${geistMono.variable} ${luckiestGuy.variable} ${playfairDisplay.variable} scroll-smooth antialiased overflow-x-hidden `}>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
